# Generated by Django 4.2.16 on 2025-05-17 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aptts', '0002_alter_feedback_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='exercisecollection',
            name='course',
        ),
        migrations.RemoveField(
            model_name='exercisecollection',
            name='order',
        ),
        migrations.AddField(
            model_name='course',
            name='pending_requests',
            field=models.ManyToManyField(blank=True, related_name='pending_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='print_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercisecollection',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='collections', to='aptts.course'),
        ),
        migrations.AddField(
            model_name='exercisecollection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercisecollection',
            name='created_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='collections_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercisecollection',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='in_collections', to='aptts.exercise'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
